### ISSUE TITLE
Android : Fatal Exception: com.tns.NativeScriptException: Attempt to use cleared object reference id=120

### ISSUE THREAD

**Issue by YudizAndroidNareshP** [THEOplayer/samples-android-sdk#28]
**Fatal Exception: com.tns.NativeScriptException: Attempt to use cleared object reference id=120
       at com.tns.Runtime.getJavaObjectByID(Runtime.java:19)
       at com.tns.Runtime.callJSMethodNative(Runtime.java)
       at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:76)
       at com.tns.Runtime.callJSMethodImpl(Runtime.java:1192)
       at com.tns.Runtime.callJSMethod(Runtime.java:1187)
       at com.tns.Runtime.callJSMethod(Runtime.java:2)
       at com.tns.Runtime.callJSMethod(Runtime.java:1)
       at com.tns.gen.com.theoplayer.mediacodec.event.EventListener.handleEvent(EventListener.java:3)
       at com.theoplayer.mediacodec.event.EventDispatcherImpl$1.run(EventDispatcherImpl.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)**

**Comment by ceyhun-o** [comment]
Hi @YudizAndroidNareshP,

Please reach out to us from our [Service Desk](https://opentelly.atlassian.net/servicedesk/customer/portal/1) and share all the details such as reproduction steps, player version and a minimal sample app if you are still having this issue.

Kind regards,
Ceyhun

**Comment by YudizAndroidNareshP** [comment]
Player Version : com.theoplayer.theoplayer-sdk-android:unified:4.12.0

![image](https://github.com/THEOplayer/samples-android-sdk/assets/141625205/066589ab-969f-46d7-a196-07f362e0d7b7)
![image](https://github.com/THEOplayer/samples-android-sdk/assets/141625205/1977335f-257b-40f9-ab6d-a2b9c203e14d)
